package.json
pnpm-lock.yaml
src/app.html
src/lib/components/MagneticElement.svelte
src/lib/components/Mouse3DTilting.svelte
src/lib/components/Section.svelte
src/lib/components/SlideOver.svelte
src/lib/ts/id.ts
src/lib/ui/Button.svelte
src/routes/+layout.svelte
src/routes/+page.svelte
tailwind.config.ts

- Prepare `Section.svelte` to get the right sizing
- Improve navbar responsiveness for large screens, change its top padding & make `scrollY` triggers accurate
- Tailwind:
- Add `width` rule for large screens (120rem/1920px)
- Add `tailwindcss-3d` for `translate-z`, `perspective` and other 3D CSS stuff (why isn't it native to TailwindCSS?)
- Add `hover-child:` variant because `hover:child:` acts like `child-hover:` for some reason
- Switch to `@babeard/svelte-heroicons` because `@rgossiaux/svelte-heroicons` [doesn't support yet Heroicons v2](https://github.com/rgossiaux/svelte-heroicons/pull/5)
- Improve buttons' readability and flexibility by allowing passing additional `class`es directly to the component

Hero section

---

.github/workflows/pages-deploy.yml

- Fix Dependabot skipping everything
- Fix jobs skipped
- Rework logic to avoid red status for unprivileged contributions

CI: Fix everything

---

.github/workflows/pages-deploy.yml

Fix/improve compatibility between SvelteKit and GitHub Pages, especially for error pages (with `+error.svelte`) that are not currently working. This works by removing any "GitHub magic sauce" by adding a `.nojekyll` file.
It could've been done by directly adding this empty file in the `/static` folder, however doing it through CI allows us to keep a platform-independent codebase and not get it polluted by yet another dot-file.
Both solutions come from [the official docs](https://kit.svelte.dev/docs/adapter-static#github-pages) for the `adapter-static` we're using.

Fix compatibility with GH pages

---

.github/workflows/auto-release.yml
package.json

Automate the release process by automatically pushing a new release with the appropriate content when the `version` field of `package.json` changes.
Also, bump the version in `package.json` because it was still `1.0.0` (this will trigger this new pipeline, but without creating a new release as it already exists)
Based on what the current releases already look like
```
- Fix lint - @WarningImHack3r
- Initial CI file - @WarningImHack3r
- Change navbar height (#120) - @MinixBF
- Improve the process section on mobile (#116) - @MinixBF
- Phone contact in Contact page (#113) - @WarningImHack3r
- Initial release fixes (#112) - @WarningImHack3r
**Full Changelog:** https://github.com/EmeraldHQ/Website/compare/v1.0.2...v1.0.2
```

Auto-release versions from CI

---

.husky/post-checkout

Rollbacks a change made on #94 that was my mistake: `git fetch -p` does _not_ replace `pnpx git-removed-branches -p`.
- `git fetch -p` only prunes **remote** branches that no longer exist
- `git-removed-branches -p` prunes **local** branches that no longer exist on remote
Adding this line back will do the trick perfectly, without any risk of desync, and the addition of `-f` prevents git from misleadingly saying that the branch is not fully merged, as advised by [the docs](https://github.com/nemisj/git-removed-branches#forcing-removal).

Fix prune not deleting local branches anymore

---

.github/workflows/auto-release.yml

- Fix the GitHub token not having release write permissions
- Migrate to the gh CLI instead of the outdated `actions/create-release` GitHub Actions

Definitely fix auto-release process

---

.github/workflows/auto-release.yml

02c0f1113e2175e8d706f54bafa3ca8a708a1530 threw an error in the Auto-Release workflow: https://github.com/EmeraldHQ/Website/actions/runs/6584967728/job/17902950964.
After inspecting the weird log, I figured out where the error was thanks to the `print` statements I added in the previous fixes.
What's happening is that during the "committer email ➜ GitHub @" retrieving phase, it was iterating over an empty element for some reason. This mysterious element doesn't meet the `if` condition, so it's headed over to the `else` block and the GitHub API call, which throws the 422 error code.
But what is that empty element that's being iterated over? I first thought of a parsing error, but that made no sense. Then I realized that the only change from the latest release (`v1.0.3`) was the Dependabot …

infra: Auto-release - Fix empty changes throwing an error

---

.github/CODEOWNERS

Automatically add reviewers to the open pull requests by using the [codeowners](https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) feature of GitHub.
They should be added automatically to review once the PR is open _and_ **not** a draft, which should make one less click to do! Another advantage: it automatically asks for reviews in Dependabot/Renovate/external PRs!
I created the team so that we don't have to edit the file ever again, reviewers _are_ the members of the team. Also, I tweaked the repo's settings to enable mandatory reviews from code owners.

infra: Automate add of reviewers to pull requests

---

src/routes/contact/+page.svelte

1-line PR, quick and easy: I just learned in [a Tweet](https://x.com/una/status/1716481290982048079) that **Chrome 119**, as well as **Safari 17**, now support `<hr>` tags into `<select>`s.
I instantly thought we could use it in the only place I've ever used a `<select>`: the Contact page.
It is not only a gimmick that I wanna use because I learned its existence: it _does_ make sense to separate "No budget" from the rest.
It also doesn't cost a thing: on an unsupported/outdated browser, it will just not work, so no issue on that side! It will naturally become available to up-to-date users, and older browsers won't make a difference before/after this PR.
So here we are, one line of change, 4 characters, here is the result:
:---: | :---:
**Before** | **After**
> [!NOTE]
> Despite the …

Add <hr> tag to the Contact page

---

.github/workflows/pages-deploy.yml
src/routes/+page.svelte

#159 did indeed make the CI faster, but also made it **always** faster: the conditions to actually use the "slow" steps seem to never be true.
~~It's weird because the bash script is correct but the output is not. Continuing investigating.~~ Update: I'm just dumb, the bug wasn't from the scripts but rather from the incorrect usage of the output variables...
- Fix conditions being overcomplicated
- Add logs to debug easier
- Break from loops whenever a condition is already met

infra: Fix faster CI never being true

---

.github/workflows/auto-release.yml

Last fix for auto release: escape HTML tags to prevent them from being interpreted by the GitHub Releases markdown.
> I really didn't get lucky: double quotes + HTML tags, I think every possible edge case has been met in those very 2 commits.
> **Good point**: now the workflow is rock solid and we will be able to use it fearlessly!

infra: Auto release - Escape HTML tags & better readability

---

.github/workflows/pr-title-changer.yml

Quick refinement PR: disable the PR Title Modifier workflow when the PR is from Dependabot or Renovate. This is for 4 reasons:
- Avoid doing a useless thing
- Avoid launching yet another workflow run on GH's servers
- Don't mix actual `infra:` PRs from us with simple dependencies updates PRs
- Avoid a (funny) robot war:

infra: Don't rename PRs if they're from Dependabot or Renovate

---

.github/renovate.json
.github/workflows/renovate-validator.yml

Renovate has not worked since #153: it never opened an npm updates PR. This is likely due to the `matchDepNames` line because it's the only one different from [Mintstone](https://github.com/WarningImHack3r/Mintstone), where it's working fine.
Additionally, `matchDepNames` didn't make sense as a key, because it's a pattern we're using, not a list of names. This change now makes more sense and is used in [a few repos](https://grep.app/search?q=excludePackagePatterns&filter[lang][0]=JSON&filter[lang][1]=JSON5).
On another hand, I think it's a shame we don't have _any_ feedback on whether the current configuration is valid or not, except for the (not useful) Mend dashboard.
Dependabot has one by default out-of-the-box, so it's a kind of regression not to have it with Renovate too.
While …

infra: Renovate - Fix config & add validation workflow

---

package.json
pnpm-lock.yaml
src/routes/+layout.svelte
src/routes/contact/+page.svelte
src/routes/sitemap.xml/+server.ts

[4 months after Prettier 3.0 and 2 months after the latest release](https://www.npmjs.com/package/prettier?activeTab=versions), Prettier finally [reimplements the plugin search feature](https://github.com/prettier/prettier/pull/15433#issuecomment-1732536900), allowing Svelte & TailwindCSS plugins to work as they did in v2, without having to specify the plugins in the command manually.
Our `Fix lint` workflow fix now works again, fixing in the meantime the files that have not been formatted in our editors for 4 months, in addition to formatting using the [improved ternary rules](https://prettier.io/blog/2023/11/13/3.1.0#javascript) in 3.1 ([other improvements](https://prettier.io/blog/2023/11/13/3.1.0#other-changes)).
> I still cannot stop enjoying how the CI progressively fixes the PR by …

infra: Fix Prettier 3 not working with plugins

---

.github/renovate.json

Renovate _still doesn't_ open PRs, despite it finding new updates... It randomly doesn't support `pnpm-lock.yaml` anymore:
After Googling the problem, I found [this recent GitHub discussion](https://github.com/renovatebot/renovate/discussions/22133) where the solution (despite having no sense) was to set the [`rangeStrategy`](https://docs.renovatebot.com/configuration-options/#rangestrategy) key in the configuration.
`"pin"` is not something we want, so I'm using `"bump"` instead.
I don't know how a config key that doesn't (seem to) impact the _lock_ file would resolve the issue, but let's try it out!
Additionally, the Renovate Config Validator workflow I made suggested upgrading from `config:base` to [`config:recommended`](https://docs.renovatebot.com/presets-config/#configrecommended), …

infra: Fix Renovate still not opening PRs

---

.github/workflows/pr-title-changer.yml

Add `package.json` to the list of files _not_ triggering the `PR Title Modifier` workflow, avoiding the change to an infra PR when we bump the version.
It won't affect the dependencies bump, because those _always_ come along with a modification of the `pnpm-lock.yaml` lock file (either by bots or by the `pre-checks` workflow), which is not ignored by this rule.

infra: Add package.json to ignored paths of title modifier workflow

---

package.json
src/routes/+page.svelte

I noticed on my iPhone that the icons were not getting their hover effect moved from one another in the Technologies section a few weeks ago.
I took a look today and noticed it was indeed not working not only in Safari for iOS but also in Safari desktop.
The code that's supposed to do it is in the `technoCards.addEventListener("scrollend", () => {});` handler. After investigation on potential causes, it turned out that the `"scrollend"` event was not working because it's [simply not implemented in Safari yet](https://caniuse.com/mdn-api_element_scrollend_event). To my surprise, it's only existed since [January 2023](https://developer.chrome.com/blog/scrollend-a-new-javascript-event/), which is still very recent.
The workaround is simple, [provided by this very article from Chrome for …

Fix icons hover not updating on scroll in Technos section on Safari

---

.github/workflows/pages-deploy.yml

Self explanatory, add (back) any dependency change to the list of changes triggering the `Check lint` workflow step.
It’s useful when ESLint/Prettier or their plugins are updated from the bots’ PRs: we need to know if they introduce breaking changes.
Also, remove `package.json` from the list of files requiring the build of the repo, because as mentioned in #189, if a dependency is changed the lock file will be changed too, and we don’t want a version bump to trigger a whole build for nothing.

infra: Add dependencies to workflow lint step

---

src/lib/shells/SlideOver.svelte
src/routes/+layout.svelte
src/routes/+page.svelte

Improve the logic used to navigate to an item from the responsive slide-over to reduce the amount of `setTimeout`s (and `setInterval`s) in the code, which are neither clean nor optimized.
Introduce callbacks powered by Svelte Headless UI to accurately get the right timing when the slide-over opens or closes. I'm moderately proud of the resulting code, if you find a cleaner way instead of resetting the function as I'm doing, don't hesitate to tell me.
This is the only place where it was a poor optimizable logic and not a requirement.
I also took advantage of this PR to remove the `close()` function in `SlideOver.svelte`, preferring duplicating and inlining twice than cluttering the `<script>` tag. Feel free to tell me if you prefer it rolled back.

Improve logic for navigating from SlideOver

---

package.json
src/routes/+page.svelte

Since the recent removal of the `"mouseleave"` event on the icons of the Technologies section in #187, clicking an icon to slide to another card doesn't reset the auto-scroll feature's timer, leading to some weird behavior of the carousel not taking in account our latest card slide.
To fix this, I'm introducing a new boolean variable called `shouldResetTechnoScrollTimer`, which is set to `true` if and only if a card is being moved from clicking an icon. Then, when the scroll ends, if this variable is true (if the card move has been triggered from an icon click), I reset the `setInterval` and set the variable back to false.
As such, it should fix the issue without causing the drawbacks we met with `"mouseleave"` on mobile.
I also used this PR to rename a bunch of variables, making what …

Fix Technologies carousel auto-scroll not resetting on click

---

src/app.css
src/lib/layouts/Section.svelte
src/lib/utils/scroll.ts
src/routes/+layout.svelte
src/routes/+page.svelte

I recently discovered (the meaning of) `scroll-padding(-X)` and `scroll-margin(-X)` CSS properties in a [Kevin Powell's video](https://youtu.be/cCAtD_BAHNw?si=6JgemZgs0pZRdv8H&t=370). I instantly realized that THIS is what we need instead of our `scroll.ts` file, so make the scroll offset by a bit _and_ more accessible with CSS only.
So that's what I just did: get rid of `scroll.ts` because the function would only contain 1 line and we already use other JS scroll methods elsewhere to scroll to the top or within carousels.
- Better accessibility with `prefers-reduce-motion`
- JS-less smooth scroll
- Less computation
- Fewer abstractions
- Less code
- A file
Looks like a win to me!

Replace JS calculation with scroll margins

---

src/lib/layouts/Section.svelte
src/routes/+page.svelte

Revert changes do before on #222 and improve sections to fit better on a large screen.
Unfortunately on the section "about us", to improve and make it incredible, we need to add something right in the future (photos or symbol)

Revert large responsive changes

---

.github/workflows/pages-deploy.yml
eslint.config.js
package.json
pnpm-lock.yaml
src/lib/elements/button/Button.svelte
src/routes/+error.svelte
src/routes/+layout.svelte

Little quality-of-life improvements!
- **ESLint**. Remove spread from config because it's not necessary anymore
- **pnpm**. Upgrade to v10 and hardcode it to avoid incompatibility issues
- **pnpm**. Add `esbuild` in the allowed `postinstall` scripts since that's needed since v10
- **pnpm/SvelteKit**. Upgrade the `"prepare"` script to [run the appropriate script since they removed theirs](https://github.com/sveltejs/kit/releases/tag/%40sveltejs%2Fkit%402.16.0) due to `v10`
- This should also remove the warnings about missing `.svelte-kit/tsconfig.json` we have during development and builds!
- **pnpm/ESLint**. Properly add `@eslint/js` to the dependencies because indirect dependencies are not working anymore with v10
- **package.json**. Remove dependency-related scripts because they’re …

infra: Little improvements
